config/routes.rb
Rails.application.routes.draw do
  root 'decisions#index'

  get 'results' => 'decisions#results'

  resources :decisions, only: [:index, :create, :new, :show, :update]
  resources :choices, only: [:create, :new]
  resources :criteriums, only: [:create, :new]
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :decision

  has_many :criteriums, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
end

app/models/criterium.rb
class Criterium < ActiveRecord::Base
  belongs_to :choice

  validates :importance, :valuation, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1,
                                                          less_than_or_equal_to: 10}
  validates :name, presence: true, length: { minimum: 5, maximum: 70 }
end

app/models/decision.rb
class Decision < ActiveRecord::Base
  belongs_to :best_abs, class_name: 'Choice'
  belongs_to :best_user, class_name: 'Choice'
  belongs_to :best_balanced, class_name: 'Choice'

  has_many :choices, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5, maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include DecisionsHelper
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  def create
    @choice = current_decision.choices.build(choice_params)
    if @choice.save
      flash[:info] = 'New choice added successfully'
      redirect_to current_decision
    else
      render 'new'
    end
  end

  def new
    @choice = current_decision.choices.build
  end

  private

    def choice_params
      params.require(:choice).permit(:name)
    end
end

app/controllers/criteriums_controller.rb
class CriteriumsController < ApplicationController

  def create
    @criterium = Criterium.new(criterium_params)
    @criterium.importance = @criterium.valuation = 5
    if @criterium.save
      flash[:info] = 'New criterium added successfully'
      redirect_to current_decision
    else
      render 'decisions/new'
    end
  end

  def new
    @criterium = Choice.find(params[:choice_id]).criteriums.build
  end

  private

    def criterium_params
      params.require(:criterium).permit(:name, :choice_id)
    end
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController

  before_action :only_current, only: [:results, :update]

  def index
    @decisions = Decision.where('best_abs_id IS NOT NULL').limit(5).order('created_at desc')
  end

  def show
    @decision = Decision.find(params[:id])
    if creator_looks?(@decision)
      @choices = @decision.choices
    else
      render 'results'
    end
  end

  def create
    @decision = Decision.new(decision_params)
    if @decision.save
      remember_decision(@decision)
      flash[:info] = 'First step finished - you have stated your decision'
      redirect_to decision_url(@decision)
    else
      render 'new'
    end
  end

  def new
    @decision = Decision.new
  end

  def update
    if correct_input?
      logger.info 'Input is correct'
      params[:importance].each do |k, v|
        v.each { |kk, vv| Criterium.find(kk.to_i).update_attribute(:importance, vv.to_i) }
      end
      params[:valuation].each do |k, v|
        v.each { |kk, vv| Criterium.find(kk.to_i).update_attribute(:valuation, vv.to_i) }
      end

      evaluate
      redirect_to results_url
    else
      logger.info 'Input is incorrect'
      flash[:danger] = 'Input is incorrect'
      redirect_to current_decision
    end
  end

  def results
    @decision = current_decision
  end

  private

    def decision_params
      params.require(:decision).permit(:name)
    end

    def only_current
      redirect_to root_url if current_decision.nil?
    end

    def creator_looks?(decision)
      return true if !current_decision.nil? && current_decision.id == decision.id
      return false
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/criteriums_helper.rb
module CriteriumsHelper
end

app/helpers/decisions_helper.rb
module DecisionsHelper

  def evaluate()
    getBestForUser()
    getBest()
    getBalanced()
  end

  def getMax(val)
    maxVal = val.values[0]
    max = val.keys[0]
    val.each { |k,v| maxVal = v, max = k if v > maxVal }
    max
  end

  def getBestForUser()
    h = Hash.new(0)
    params[:importance].each { |k, v| v.each { |kk, vv| h[k] += vv.to_i * params[:valuation][kk].to_i } }
    current_decision.update_attribute(:best_user_id, getMax(h))
  end

  def getBest()
    h = Hash.new(0)
    params[:importance].each { |k, v| v.each { |kk, vv| h[k] += vv.to_i } }
    current_decision.update_attribute(:best_abs_id, getMax(h))
  end

  def getBalanced()
    h = Hash.new(0)
    coef = 4
    params[:importance].each do |k, v|
      v.each do |kk, vv|
        h[k] -= (coef - vv.to_i) * params[:valuation][kk].to_i if vv.to_i < coef
        h[k] += vv.to_i * params[:valuation][kk].to_i
      end
    end
    current_decision.update_attribute(:best_balanced_id, getMax(h))
  end

  def remember_decision(decision)
    session[:decision_id] = decision.id
  end

  def forget_decision
    session[:decision_id] = nil
  end

  def current_decision
    decision_id = session[:decision_id]
    unless (decision_id.nil?)
      @decision = Decision.find(decision_id)
    else
      nil
    end
  end

  def correct_input?
    return false if params[:importance].nil? || params[:valuation].nil?
    params[:importance].each { |k, choice| return false if choice.empty? }
    params[:valuation].each { |k, choice| return false if choice.empty? }
    return true
  end

end

app/views/choices/_choice.html.erb
<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--6-col" style="width: 100%">
  <div class="mdl-card__title mdl-card--expand" style="background-color: #0091ea">
    <h2 class="mdl-card__title-text"><%= choice.name %></h2>
  </div>

  <div class="mdl-card__actions mdl-card--border">

    <% if choice.criteriums.any? %>
        <table>
          <thead>
            <tr>
              <th style="width: 400px;">Criteria</th>
              <th>Importance</th>
              <th>Valuation</th>
            </tr>
          </thead>

          <tbody>
            <%= render partial: 'criteriums/criterium', collection: choice.criteriums %>
          </tbody>
        </table>
    <% end %>
  </div>

  <div>
    <%= button_to 'Add criteria', new_criterium_path, method: :get,
                  class: 'add-criteria-btn mdl-button mdl-js-button mdl-button--raised mdl-button--accent',
                  params: { choice_id: choice.id } %>
  </div>
</div>

app/views/choices/new.html.erb
<div class="mdl-grid">
  <div class="dec-inp__form-card mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col">
    <div class="dec-inp__form">
      <%= form_for(@choice) do |f| %>
          <div class="mdl-textfield mdl-js-textfield">
            <%= f.label :name, class: 'mdl-textfield__label' %>
            <%= f.text_area :name, class: 'mdl-textfield__input' %>
          </div>

          <%= f.submit 'Add', class: 'shop-form-btn mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
      <% end %>
    </div>
  </div>
</div>

app/views/criteriums/_criterium.html.erb
<div>
  <tr>
    <td><%= criterium.name %></td>
    <td>
      <div style="width: 240px;">
        <input class="mdl-slider mdl-js-slider" type="range"
               name="importance[<%= criterium.choice.id %>][<%= criterium.id %>]"
               min="1" max="10" value="<%= criterium.importance %>" tabindex="0">
      </div>
    </td>
    <td>
      <div style="width: 240px;">
        <input class="mdl-slider mdl-js-slider" type="range"
               name="valuation[<%= criterium.choice.id %>][<%= criterium.id %>]"
               min="1" max="10" value="<%= criterium.valuation %>" tabindex="0">
      </div>
    </td>
  </tr>
</div>

app/views/criteriums/new.html.erb
<div class="mdl-grid">
  <div class="dec-inp__form-card mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col">
    <div class="dec-inp__form">
      <%= form_for(@criterium, url: criteriums_path) do |f| %>
          <div class="mdl-textfield mdl-js-textfield">
            <%= f.label :name, class: 'mdl-textfield__label' %>
            <%= f.text_area :name, class: 'mdl-textfield__input' %>
          </div>

          <%= f.hidden_field :choice_id %>

          <%= f.submit 'Add', class: 'shop-form-btn mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
      <% end %>
    </div>
  </div>
</div>

app/views/decisions/index.html.erb
<div class="dec-inp__form-card mdl-card mdl-shadow--2dp mdl-cell mdl-cell--8-col">
  <h2>Last made decisions</h2>

  <div>
    <table style="margin-left: auto; margin-right: auto;">
      <thead>
      <tr>
        <th style="width: 300px;">Decision</th>
        <th style="width: 150px;">Best absolute</th>
        <th style="width: 150px;">Best for user</th>
        <th style="width: 150px;">Best balanced</th>
      </tr>
      </thead>

      <tbody>
        <% @decisions.each do |d| %>
          <tr>
            <th><%= link_to d.name, d %></th>
            <th><%= d.best_abs.name %></th>
            <th><%= d.best_user.name %></th>
            <th><%= d.best_balanced.name %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div style="margin-right: auto; margin-left: auto; margin-top: 20px;margin-bottom: 20px;">
    <%= link_to 'MAKE DECISION', new_decision_path,
                class: 'add-criteria-btn mdl-button mdl-js-button mdl-button--raised mdl-button--colored'%>
  </div>
</div>

app/views/decisions/new.html.erb
<div class="dec-inp__form-card mdl-card mdl-shadow--2dp mdl-cell mdl-cell--4-col">
  <div class="dec-inp__form">
    <%= form_for(@decision) do |f| %>
        <div class="mdl-textfield mdl-js-textfield">
          <%= f.label :name, class: 'mdl-textfield__label' %>
          <%= f.text_area :name, class: 'mdl-textfield__input' %>
        </div>

        <%= f.submit 'Submit', class: 'shop-form-btn mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
    <% end %>
  </div>
</div>

app/views/decisions/results.html.erb
<h1>Results of calculations</h1>

<div class="mdl-grid">
    <div id="best_abs" class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title mdl-card--expand" style="background-color: #00796b">
        <h2 class="mdl-card__title-text">Best </h2>
      </div>

      <div class="mdl-card__supporting-text">
        <%= @decision.best_abs.name %>
      </div>
    </div>

    <div id="best_usr" class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title mdl-card--expand" style="background-color: #03a9f4">
        <h2 class="mdl-card__title-text">Best for user</h2>
      </div>

      <div class="mdl-card__supporting-text">
        <%= @decision.best_user.name %>
      </div>
    </div>

    <div id="best_bal" class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--2dp">
      <div class="mdl-card__title mdl-card--expand" style="background-color: #9fa8da">
        <h2 class="mdl-card__title-text">Best balanced</h2>
      </div>

      <div class="mdl-card__supporting-text">
        <%= @decision.best_balanced.name %>
      </div>
    </div>
</div>

app/views/decisions/show.html.erb
<div class="mdl-grid">
  <div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--3-col"
       style="max-height: 200px">

    <div id="dec_name">
      <div id="decision_name"><%= @decision.name %></div>

      <%= form_tag @decision, method: :put do %>
          <div id="hidden_inputs">
            <% @decision.choices.each do |choice| %>
                <% choice.criteriums.each do |criterium| %>
                    <input type="hidden" name="importance[<%= choice.id %>][<%= criterium.id %>]"
                           value="<%= criterium.importance %>">
                    <input type="hidden" name="valuation[<%= choice.id %>][<%= criterium.id %>]"
                           value="<%= criterium.valuation %>">
                <% end %>
            <% end %>
          </div>

          <div class="btn-center">
            <%= submit_tag 'Find best', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
          </div>
      <% end %>
    </div>

  </div>

  <div id="choices_holder" class="mdl-cell mdl-cell--8-col">

    <% if @choices.any? %>
        <%= render @choices %>
    <% end %>

    <div style="margin-left: 8px;">
      <%= button_to 'Add choice', new_choice_path, method: :get,
                    class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__left-section">
    <div class="mdl-logo">DecisionHelper</div>
    <ul class="mdl-mini-footer__link-list">
      <li>
        <a href="https://www.facebook.com/profile.php?id=100010481281269">Михайло Ящук</a>
      </li>
      <li><a href="http://vk.com/id21595494">Дмитрій Ільчук</a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="mdl-layout__header mdl-color--transparent">
  <div class="mdl-layout__header-row">
    <!-- Title -->
    <a class="mdl-navigation__link" href="<%= root_url %>">DecisionHelper</a>
    <!-- Add spacer, to align navigation to the right -->
    <div class="mdl-layout-spacer"></div>

    <!-- Navigation -->
    <nav class="mdl-navigation">
      <!--<a class="mdl-navigation__link" href="#">oop</a>-->
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>DecisionHelper</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <!--<link rel="stylesheet" href="material.blue-orange.min.css">-->
      <!--<script src="material.min.js"></script>-->
      <!--<link rel="stylesheet" href="icon.css">-->
      <%= csrf_meta_tags %>
    </head>

    <body class="mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
        <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
          <%= render 'layouts/header' %>
          <main class="mdl-layout__content">
            <% flash.each do |mes_type, mes| %>
                <div class="alert alert-<%= mes_type %>"><%= mes %></div>
            <% end %>
            <%= yield %>
          </main>
          <%= render 'layouts/footer' %>
        </div>
    </body>
</html>

app/views/shared/_choice_form.html.erb
<div class="mdl-card mdl-shadow--2dp mdl-cell mdl-cell--6-col">
  <%= form_for @choice, url: choices_path do |f| %>
      <div class="mdl-textfield mdl-js-textfield">
        <%= f.label :name, class: 'mdl-textfield__label' %>
        <%= f.text_field :name, class: 'mdl-textfield__input' %>
      </div>

      <%= f.submit 'Add', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
  <% end %>
</div>

app/views/shared/_criterium_form.html.erb
<div>
  <%= form_for @criterium, url: criteriums_path do |f| %>
      <div class="mdl-textfield mdl-js-textfield">
        <%= f.label :name, class: 'mdl-textfield__label' %>
        <%= f.text_field :name, class: 'mdl-textfield__input' %>
      </div>

      <%= f.hidden_field :choice %>

      <%= f.submit 'Add', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' do %>
          <i class="material-icons">add</i>
      <% end %>
  <% end %>
</div>